# This rule is not used by the project cluster itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to term.cts.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/managed-by: kustomize
  name: term-cloudterm-viewer-role
rules:
- apiGroups:
  - term.cts.io
  resources:
  - cloudterms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - term.cts.io
  resources:
  - cloudterms/status
  verbs:
  - get
