/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	termv1 "cluster/api/term/v1"
)

// NetworkApplyConfiguration represents a declarative configuration of the Network type for use
// with apply.
type NetworkApplyConfiguration struct {
	PortApplyConfiguration `json:",inline"`
	EIP                    *string `json:"eip,omitempty"`
}

// NetworkApplyConfiguration constructs a declarative configuration of the Network type for use with
// apply.
func Network() *NetworkApplyConfiguration {
	return &NetworkApplyConfiguration{}
}

// WithNetworkID sets the NetworkID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkID field is set to the value of the last call.
func (b *NetworkApplyConfiguration) WithNetworkID(value string) *NetworkApplyConfiguration {
	b.PortApplyConfiguration.NetworkID = &value
	return b
}

// WithFixedIPs adds the given value to the FixedIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FixedIPs field.
func (b *NetworkApplyConfiguration) WithFixedIPs(values ...**termv1.FixedIP) *NetworkApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFixedIPs")
		}
		b.PortApplyConfiguration.FixedIPs = append(b.PortApplyConfiguration.FixedIPs, *values[i])
	}
	return b
}

// WithSecurityGroups adds the given value to the SecurityGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecurityGroups field.
func (b *NetworkApplyConfiguration) WithSecurityGroups(values ...string) *NetworkApplyConfiguration {
	for i := range values {
		b.PortApplyConfiguration.SecurityGroups = append(b.PortApplyConfiguration.SecurityGroups, values[i])
	}
	return b
}

// WithEIP sets the EIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EIP field is set to the value of the last call.
func (b *NetworkApplyConfiguration) WithEIP(value string) *NetworkApplyConfiguration {
	b.EIP = &value
	return b
}
