/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	termv1 "cluster/api/term/v1"
)

// NetworkStatusApplyConfiguration represents a declarative configuration of the NetworkStatus type for use
// with apply.
type NetworkStatusApplyConfiguration struct {
	PortStatusApplyConfiguration `json:",inline"`
	EIP                          *string `json:"eip,omitempty"`
}

// NetworkStatusApplyConfiguration constructs a declarative configuration of the NetworkStatus type for use with
// apply.
func NetworkStatus() *NetworkStatusApplyConfiguration {
	return &NetworkStatusApplyConfiguration{}
}

// WithNetworkID sets the NetworkID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkID field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithNetworkID(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.NetworkID = &value
	return b
}

// WithFixedIPs adds the given value to the FixedIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FixedIPs field.
func (b *NetworkStatusApplyConfiguration) WithFixedIPs(values ...**termv1.FixedIP) *NetworkStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFixedIPs")
		}
		b.PortStatusApplyConfiguration.FixedIPs = append(b.PortStatusApplyConfiguration.FixedIPs, *values[i])
	}
	return b
}

// WithSecurityGroups adds the given value to the SecurityGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecurityGroups field.
func (b *NetworkStatusApplyConfiguration) WithSecurityGroups(values ...string) *NetworkStatusApplyConfiguration {
	for i := range values {
		b.PortStatusApplyConfiguration.SecurityGroups = append(b.PortStatusApplyConfiguration.SecurityGroups, values[i])
	}
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithID(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.ID = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithAdminStateUp(value bool) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.AdminStateUp = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithStatus(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.Status = &value
	return b
}

// WithMacAddress sets the MacAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MacAddress field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithMacAddress(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.MacAddress = &value
	return b
}

// WithTenantID sets the TenantID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantID field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithTenantID(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.TenantID = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithProjectID(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.ProjectID = &value
	return b
}

// WithPortID sets the PortID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortID field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithPortID(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.PortID = &value
	return b
}

// WithPortReady sets the PortReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortReady field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithPortReady(value bool) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.PortReady = &value
	return b
}

// WithIfname sets the Ifname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ifname field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithIfname(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.Ifname = &value
	return b
}

// WithNicname sets the Nicname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Nicname field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithNicname(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.Nicname = &value
	return b
}

// WithIfaceid sets the Ifaceid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ifaceid field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithIfaceid(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.Ifaceid = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithInterface(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.Interface = &value
	return b
}

// WithDeviceReady sets the DeviceReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceReady field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithDeviceReady(value bool) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.DeviceReady = &value
	return b
}

// WithVifType sets the VifType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VifType field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithVifType(value string) *NetworkStatusApplyConfiguration {
	b.PortStatusApplyConfiguration.VifType = &value
	return b
}

// WithEIP sets the EIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EIP field is set to the value of the last call.
func (b *NetworkStatusApplyConfiguration) WithEIP(value string) *NetworkStatusApplyConfiguration {
	b.EIP = &value
	return b
}
