# jaeger-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.40
        env:
        - name: COLLECTOR_OTLP_ENABLED  # 启用 OTLP 接收器
          value: "true"
        ports:
        - containerPort: 4317  # OTLP gRPC 端口
          name: otlp-grpc
        - containerPort: 16686 # Web UI
          name: web-ui
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: web-ui
      port: 16686
      targetPort: 16686
  type: ClusterIP
